

service: jwilderspin-data

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  contact:
    handler: src/contact/handler.index
    events:
      - http:
          method: post
          path: contact
          cors: true
